#
# Example Sieb configuration file.
#

# Default, no logging.  Relative to homedir.
logfile: sieb.log

## Rules tried before global filtering
early_rules:
  -
    headers:
      TO: mhlon@(laika|ravn)
      received: .*sendgrid.*
    filter:
      - [ reformail, -A, "X-Sieb: This matched." ]
    deliver: .whatever

## Filter message before additional rules.
filter:
  - [ reformail, -A, "X-Sieb: Processed!" ]

## Ordered, top down, first match wins.
## Headers are lowercased.  Multiple matches are AND'ed.
##
## Delivery default is ~/Maildir, any set value is an auto-created maildir under
## that path.
##
rules:
  -
    headers:
      x-sieb: global
    deliver: .whoas

  # # Magic "TO" which means To: OR Cc:
  # -
  #   headers:
  #     TO: regexp
  #   deliver: .whereever
   
  # # Filter message through reformail, then deliver to ~/Maildir.
  # -
  #   headers:
  #     x-what: fuckery
  #     filter: reformail ...


