#
# Example Sieb configuration file.
#

# Default, no logging.  Relative to homedir.
#logfile: sieb.log

## Rules tried before global filtering
early_rules:
  -
    headers:
      to: mahlon@(laika|ravn)
      received: .*sendgrid.*
    filter:
      - [ reformail, -A, "X-Sieb: This matched." ]
    deliver: .whatever

## Filter message before additional rules.
filter:
  - [ reformail, -A, "X-Sieb: That shit totally matched" ]

## Ordered, top down, first match wins.
## Headers are lowercased.  Multiple matches are AND'ed.
##
## Delivery default is ~/Maildir, any set value is an auto-created maildir under
## that path.
##
# rules:
#   -
#     headers:
#       x-what: pcre-matcher
#       poonie: pcre-matcher
#     deliver: .whatever

  # # Magic "TO" which means To: OR Cc:
  # -
  #   headers:
  #     TO: regexp
  #   deliver: .whereever
   
  # # Filter message through reformail, then deliver to ~/Maildir.
  # -
  #   headers:
  #     x-what: fuckery
  #     filter: reformail ...


